<robot name="mycar" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 雷达部件 -->
    <!-- 参数 -->

    <!-- 1.支架 尺寸：半径、高度   关节偏移量
   -->
 <xacro:property name="support_radius"  value="0.01"/>
 <xacro:property name="support_length" value="0.15"/>
 <xacro:property name="laser_radius" value="0.03"/>
 <xacro:property name="laser_length" value="0.05"/>



 <xacro:property name="joint_suport_x" value="0"/>
 <xacro:property name="joint_suport_y" value="0"/>
 <xacro:property name="joint_suport_z" value="${base_length / 2 + support_length / 2}"/>
 <!-- z=车体高度/2 + 支架高度/2 -->
 <xacro:property name="joint_laser_x" value="0"/>
 <xacro:property name="joint_laser_y" value="0"/>
 <xacro:property name="joint_laser_z" value="${support_length / 2 + laser_length / 2}"/>
 <!-- z=支架高度/2+雷达高度/2 -->
 
 <!-- 支架    -->
    <link name="support">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}"/>
            </geometry>
            <material name="yellow">
                <color rgba="0.8 0.5 0.0 0.5"/>
            </material>
        </visual>
    </link>
   <joint name="support2base" type="fixed">
    <origin xyz="${joint_suport_x} ${joint_suport_y} ${joint_suport_z}" rpy="0.0 0.0 0.0"/>
    <parent link="base_link"/>
    <child link="support"/>
    <axis xyz="0.0 0.0 0.0"/>
   </joint>
    <!-- 2.雷达  雷达尺寸：半径  高度
    关节偏移量：x y z -->
 <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}"/>
            </geometry>
            <material name="red">
                <color rgba="1.0 0.0 0.0 0.5"/>
            </material>
        </visual>
    </link>
   <joint name="laser2support" type="fixed">
        <origin xyz="${joint_laser_x} ${joint_laser_y} ${joint_laser_z}" rpy="0.0 0.0 0.0"/>
        <parent link="support"/>
        <child link="laser"/>
        <axis xyz="0.0 0.0 0.0"/>
   </joint>

</robot>